spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp_stu
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1111


mybatis-plus:
  # 指定xml文件路径
  mapper-locations: classpath*:mybatis/*.xml
  # 指定实体对象的扫描包
  type-aliases-package: study.hxl.mp.bean
  configuration:
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 删除状态的值为 1
      logic-delete-value: 1
      # 未删除状态的值为 0  1和0这两个值是默认的 不设置也可以，可以自己设置为其他的
      logic-not-delete-value: 0
  # 指定枚举类的包 扫描
  type-enums-package: study.hxl.mp.enums